new_data=data[,c("AMT_CREDIT","AMT_ANNUITY","AMT_GOODS_PRICE","DAYS_BIRTH","DAYS_REGISTRATION",
                  "DAYS_ID_PUBLISH","REGION_RATING_CLIENT","REGION_RATING_CLIENT_W_CITY","EXT_SOURCE_2","DEF_30_CNT_SOCIAL_CIRCLE",
                  "DAYS_LAST_PHONE_CHANGE","OWN_CAR_AGE","OCCUPATION_TYPE","NAME_FAMILY_STATUS","NAME_HOUSING_TYPE","ORGANIZATION_TYPE",
                  "NAME_EDUCATION_TYPE")]


#save(new_data,file="final_dataset.Rdata")